// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"teamplayer/ent/message"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Message is the model entity for the Message schema.
type Message struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MessageUUID holds the value of the "message_uuid" field.
	MessageUUID uuid.UUID `json:"message_uuid,omitempty"`
	// Sender holds the value of the "sender" field.
	Sender string `json:"sender,omitempty"`
	// Receiver holds the value of the "receiver" field.
	Receiver string `json:"receiver,omitempty"`
	// SendDate holds the value of the "send_date" field.
	SendDate time.Time `json:"send_date,omitempty"`
	// ReceivedDate holds the value of the "received_date" field.
	ReceivedDate time.Time `json:"received_date,omitempty"`
	// Message holds the value of the "message" field.
	Message      []string `json:"message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Message) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case message.FieldMessage:
			values[i] = new([]byte)
		case message.FieldID:
			values[i] = new(sql.NullInt64)
		case message.FieldSender, message.FieldReceiver:
			values[i] = new(sql.NullString)
		case message.FieldSendDate, message.FieldReceivedDate:
			values[i] = new(sql.NullTime)
		case message.FieldMessageUUID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Message fields.
func (_m *Message) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case message.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case message.FieldMessageUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field message_uuid", values[i])
			} else if value != nil {
				_m.MessageUUID = *value
			}
		case message.FieldSender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender", values[i])
			} else if value.Valid {
				_m.Sender = value.String
			}
		case message.FieldReceiver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field receiver", values[i])
			} else if value.Valid {
				_m.Receiver = value.String
			}
		case message.FieldSendDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field send_date", values[i])
			} else if value.Valid {
				_m.SendDate = value.Time
			}
		case message.FieldReceivedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_date", values[i])
			} else if value.Valid {
				_m.ReceivedDate = value.Time
			}
		case message.FieldMessage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Message); err != nil {
					return fmt.Errorf("unmarshal field message: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Message.
// This includes values selected through modifiers, order, etc.
func (_m *Message) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Message.
// Note that you need to call Message.Unwrap() before calling this method if this Message
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Message) Update() *MessageUpdateOne {
	return NewMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Message entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Message) Unwrap() *Message {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Message is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Message) String() string {
	var builder strings.Builder
	builder.WriteString("Message(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("message_uuid=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageUUID))
	builder.WriteString(", ")
	builder.WriteString("sender=")
	builder.WriteString(_m.Sender)
	builder.WriteString(", ")
	builder.WriteString("receiver=")
	builder.WriteString(_m.Receiver)
	builder.WriteString(", ")
	builder.WriteString("send_date=")
	builder.WriteString(_m.SendDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("received_date=")
	builder.WriteString(_m.ReceivedDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(fmt.Sprintf("%v", _m.Message))
	builder.WriteByte(')')
	return builder.String()
}

// Messages is a parsable slice of Message.
type Messages []*Message
