// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"teamplayer/ent/message"
	"teamplayer/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageUUID sets the "message_uuid" field.
func (_u *MessageUpdate) SetMessageUUID(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetMessageUUID(v)
	return _u
}

// SetNillableMessageUUID sets the "message_uuid" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableMessageUUID(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetMessageUUID(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *MessageUpdate) SetSender(v string) *MessageUpdate {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSender(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetReceiver sets the "receiver" field.
func (_u *MessageUpdate) SetReceiver(v string) *MessageUpdate {
	_u.mutation.SetReceiver(v)
	return _u
}

// SetNillableReceiver sets the "receiver" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableReceiver(v *string) *MessageUpdate {
	if v != nil {
		_u.SetReceiver(*v)
	}
	return _u
}

// SetSendDate sets the "send_date" field.
func (_u *MessageUpdate) SetSendDate(v time.Time) *MessageUpdate {
	_u.mutation.SetSendDate(v)
	return _u
}

// SetNillableSendDate sets the "send_date" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSendDate(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetSendDate(*v)
	}
	return _u
}

// SetReceivedDate sets the "received_date" field.
func (_u *MessageUpdate) SetReceivedDate(v time.Time) *MessageUpdate {
	_u.mutation.SetReceivedDate(v)
	return _u
}

// SetNillableReceivedDate sets the "received_date" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableReceivedDate(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetReceivedDate(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *MessageUpdate) SetMessage(v []string) *MessageUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// AppendMessage appends value to the "message" field.
func (_u *MessageUpdate) AppendMessage(v []string) *MessageUpdate {
	_u.mutation.AppendMessage(v)
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *MessageUpdate) ClearMessage() *MessageUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageUUID(); ok {
		_spec.SetField(message.FieldMessageUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(message.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Receiver(); ok {
		_spec.SetField(message.FieldReceiver, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendDate(); ok {
		_spec.SetField(message.FieldSendDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedDate(); ok {
		_spec.SetField(message.FieldReceivedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(message.FieldMessage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldMessage, value)
		})
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(message.FieldMessage, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetMessageUUID sets the "message_uuid" field.
func (_u *MessageUpdateOne) SetMessageUUID(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetMessageUUID(v)
	return _u
}

// SetNillableMessageUUID sets the "message_uuid" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableMessageUUID(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetMessageUUID(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *MessageUpdateOne) SetSender(v string) *MessageUpdateOne {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSender(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetReceiver sets the "receiver" field.
func (_u *MessageUpdateOne) SetReceiver(v string) *MessageUpdateOne {
	_u.mutation.SetReceiver(v)
	return _u
}

// SetNillableReceiver sets the "receiver" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableReceiver(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetReceiver(*v)
	}
	return _u
}

// SetSendDate sets the "send_date" field.
func (_u *MessageUpdateOne) SetSendDate(v time.Time) *MessageUpdateOne {
	_u.mutation.SetSendDate(v)
	return _u
}

// SetNillableSendDate sets the "send_date" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSendDate(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetSendDate(*v)
	}
	return _u
}

// SetReceivedDate sets the "received_date" field.
func (_u *MessageUpdateOne) SetReceivedDate(v time.Time) *MessageUpdateOne {
	_u.mutation.SetReceivedDate(v)
	return _u
}

// SetNillableReceivedDate sets the "received_date" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableReceivedDate(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetReceivedDate(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *MessageUpdateOne) SetMessage(v []string) *MessageUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// AppendMessage appends value to the "message" field.
func (_u *MessageUpdateOne) AppendMessage(v []string) *MessageUpdateOne {
	_u.mutation.AppendMessage(v)
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *MessageUpdateOne) ClearMessage() *MessageUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageUUID(); ok {
		_spec.SetField(message.FieldMessageUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(message.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Receiver(); ok {
		_spec.SetField(message.FieldReceiver, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendDate(); ok {
		_spec.SetField(message.FieldSendDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedDate(); ok {
		_spec.SetField(message.FieldReceivedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(message.FieldMessage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldMessage, value)
		})
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(message.FieldMessage, field.TypeJSON)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
