// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"teamplayer/ent/message"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetMessageUUID sets the "message_uuid" field.
func (_c *MessageCreate) SetMessageUUID(v uuid.UUID) *MessageCreate {
	_c.mutation.SetMessageUUID(v)
	return _c
}

// SetNillableMessageUUID sets the "message_uuid" field if the given value is not nil.
func (_c *MessageCreate) SetNillableMessageUUID(v *uuid.UUID) *MessageCreate {
	if v != nil {
		_c.SetMessageUUID(*v)
	}
	return _c
}

// SetSender sets the "sender" field.
func (_c *MessageCreate) SetSender(v string) *MessageCreate {
	_c.mutation.SetSender(v)
	return _c
}

// SetReceiver sets the "receiver" field.
func (_c *MessageCreate) SetReceiver(v string) *MessageCreate {
	_c.mutation.SetReceiver(v)
	return _c
}

// SetSendDate sets the "send_date" field.
func (_c *MessageCreate) SetSendDate(v time.Time) *MessageCreate {
	_c.mutation.SetSendDate(v)
	return _c
}

// SetNillableSendDate sets the "send_date" field if the given value is not nil.
func (_c *MessageCreate) SetNillableSendDate(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetSendDate(*v)
	}
	return _c
}

// SetReceivedDate sets the "received_date" field.
func (_c *MessageCreate) SetReceivedDate(v time.Time) *MessageCreate {
	_c.mutation.SetReceivedDate(v)
	return _c
}

// SetNillableReceivedDate sets the "received_date" field if the given value is not nil.
func (_c *MessageCreate) SetNillableReceivedDate(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetReceivedDate(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *MessageCreate) SetMessage(v []string) *MessageCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MessageCreate) SetID(v int) *MessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MessageMutation object of the builder.
func (_c *MessageCreate) Mutation() *MessageMutation {
	return _c.mutation
}

// Save creates the Message in the database.
func (_c *MessageCreate) Save(ctx context.Context) (*Message, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageCreate) defaults() {
	if _, ok := _c.mutation.MessageUUID(); !ok {
		v := message.DefaultMessageUUID()
		_c.mutation.SetMessageUUID(v)
	}
	if _, ok := _c.mutation.SendDate(); !ok {
		v := message.DefaultSendDate()
		_c.mutation.SetSendDate(v)
	}
	if _, ok := _c.mutation.ReceivedDate(); !ok {
		v := message.DefaultReceivedDate()
		_c.mutation.SetReceivedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageCreate) check() error {
	if _, ok := _c.mutation.MessageUUID(); !ok {
		return &ValidationError{Name: "message_uuid", err: errors.New(`ent: missing required field "Message.message_uuid"`)}
	}
	if _, ok := _c.mutation.Sender(); !ok {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required field "Message.sender"`)}
	}
	if _, ok := _c.mutation.Receiver(); !ok {
		return &ValidationError{Name: "receiver", err: errors.New(`ent: missing required field "Message.receiver"`)}
	}
	if _, ok := _c.mutation.SendDate(); !ok {
		return &ValidationError{Name: "send_date", err: errors.New(`ent: missing required field "Message.send_date"`)}
	}
	if _, ok := _c.mutation.ReceivedDate(); !ok {
		return &ValidationError{Name: "received_date", err: errors.New(`ent: missing required field "Message.received_date"`)}
	}
	return nil
}

func (_c *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MessageUUID(); ok {
		_spec.SetField(message.FieldMessageUUID, field.TypeUUID, value)
		_node.MessageUUID = value
	}
	if value, ok := _c.mutation.Sender(); ok {
		_spec.SetField(message.FieldSender, field.TypeString, value)
		_node.Sender = value
	}
	if value, ok := _c.mutation.Receiver(); ok {
		_spec.SetField(message.FieldReceiver, field.TypeString, value)
		_node.Receiver = value
	}
	if value, ok := _c.mutation.SendDate(); ok {
		_spec.SetField(message.FieldSendDate, field.TypeTime, value)
		_node.SendDate = value
	}
	if value, ok := _c.mutation.ReceivedDate(); ok {
		_spec.SetField(message.FieldReceivedDate, field.TypeTime, value)
		_node.ReceivedDate = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(message.FieldMessage, field.TypeJSON, value)
		_node.Message = value
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (_c *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Message, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
